import type { Metadata } from "next";
import { LegalLayout } from "@/components/LegalLayout";
import { JsonLd } from "@/components/JsonLd";
import { absoluteUrl, createPageMetadata, siteConfig } from "@/lib/seo";

export const metadata: Metadata = createPageMetadata({
  title: "Terms & Conditions",
  description: "Terms and conditions for using Master Prompt, including acceptable use and account policies.",
  path: "/terms",
});

export default function TermsPage() {
  return (
    <>
      <JsonLd
        data={{
          "@context": "https://schema.org",
          "@type": "WebPage",
          name: "Terms & Conditions",
          description: "Terms and conditions for using Master Prompt.",
          url: absoluteUrl("/terms"),
          isPartOf: { "@type": "WebSite", name: siteConfig.name },
        }}
      />
      <LegalLayout title="Terms & Conditions" updated="June 24, 2026">
      <p>
        These Terms & Conditions (&quot;Terms&quot;) govern your use of Master Prompt
        (&quot;the Service&quot;, &quot;we&quot;, &quot;us&quot;). By accessing or using the Service, you agree to
        these Terms. If you do not agree, do not use the Service.
      </p>

      <h2>1. Description of the Service</h2>
      <p>
        Master Prompt is a developer tool that transforms short ideas into structured,
        state-machine system prompts for AI agents. The Service may be self-hosted or deployed
        on infrastructure you control.
      </p>

      <h2>2. Eligibility</h2>
      <p>
        You must be at least 13 years old (or the minimum age required in your jurisdiction) to
        use the Service. You are responsible for ensuring your use complies with all applicable
        laws and the terms of your chosen AI provider.
      </p>

      <h2>3. Your API keys and accounts</h2>
      <p>
        You are solely responsible for API keys and credentials you use with the Service. API
        keys are stored locally in your browser using encryption and are not retained on our
        servers, as described in our{" "}
        <a href="/privacy" className="text-accent underline">Privacy Policy</a>.
      </p>
      <p>
        You must not share your API keys with others or use keys you are not authorized to use.
        Any charges incurred through your AI provider account are your responsibility.
      </p>

      <h2>4. Acceptable use</h2>
      <p>You agree not to use the Service to:</p>
      <ul>
        <li>Generate content that violates applicable law or third-party rights</li>
        <li>Produce malware, spam, harassment, or illegal material</li>
        <li>Attempt to reverse-engineer, abuse, or overload the Service or connected APIs</li>
        <li>Circumvent rate limits or security measures</li>
        <li>Misrepresent generated prompts as human-authored professional legal or medical advice</li>
      </ul>

      <h2>5. AI-generated output</h2>
      <p>
        Outputs are generated by third-party AI models and are provided &quot;as is&quot;. We do not
        guarantee accuracy, completeness, or fitness for a particular purpose. You are
        responsible for reviewing, editing, and validating all generated prompts before use in
        production systems.
      </p>

      <h2>6. Intellectual property</h2>
      <p>
        You retain ownership of the ideas and prompts you submit. Subject to your AI
        provider&apos;s terms, you own the outputs generated from your inputs. The Master Prompt
        application name, UI, and underlying software remain the property of the project
        contributors and licensors.
      </p>

      <h2>7. Third-party services</h2>
      <p>
        The Service integrates with third-party AI providers (OpenAI, Anthropic, Google, Groq) and
        OAuth sign-in providers (Google and GitHub only). Your use of those services is governed by
        their respective terms and privacy policies. We are not responsible for third-party
        outages, pricing changes, or policy enforcement.
      </p>

      <h2>8. Disclaimer of warranties</h2>
      <p>
        THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND,
        WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF
        MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
      </p>

      <h2>9. Limitation of liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT,
        INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA,
        OR GOODWILL, ARISING FROM YOUR USE OF THE SERVICE OR AI-GENERATED OUTPUTS.
      </p>

      <h2>10. Indemnification</h2>
      <p>
        You agree to indemnify and hold harmless the Service operators from any claims, damages,
        or expenses arising from your use of the Service, your content, or your violation of
        these Terms.
      </p>

      <h2>11. Termination</h2>
      <p>
        We may suspend or restrict access to the Service if you violate these Terms. You may
        stop using the Service at any time by discontinuing use and clearing local data.
      </p>

      <h2>12. Changes to these Terms</h2>
      <p>
        We may modify these Terms at any time. Continued use of the Service after changes are
        posted constitutes acceptance of the revised Terms. The &quot;Last updated&quot; date indicates
        the latest revision.
      </p>

      <h2>13. Governing law</h2>
      <p>
        These Terms are governed by the laws applicable in your jurisdiction of residence or the
        jurisdiction where the Service operator is established, without regard to conflict-of-law
        principles. Disputes shall be resolved in the courts of competent jurisdiction.
      </p>

      <h2>14. Contact</h2>
      <p>
        For questions about these Terms, contact us through the repository or support channel
        associated with your deployment of Master Prompt.
      </p>
    </LegalLayout>
    </>
  );
}
